# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dockercloud/hello-world
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 80

Deployment:
  appName: helloworld
