apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "my-app.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "nginx-controller"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "my-app.controller.fullname" . }}

