apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-service
spec:
  selector:
    app: {{ .Values.Deployment.appName }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}